#!/bin/sh

std="--constraints haswell --experiment sc17b --iterations 1 \
      --overcommit enable --tag try8 --tests deltafs \
      --skipreads --env XX_BYPASS_WRITE=1 --env XX_SKIP_MON=0 --env 
SHUFFLE_Buffer_per_queue=32768"

./vpicexpt_gen.pl ${std} --run 6 --dw off .

exit 0
